---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# fazhthemes

<!-- badges: start -->
<!-- badges: end -->

The goal of fazhthemes is to contain my personal {ggplot2} themes.

## Installation

You can install the development version of fazhthemes from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("fazepher/fazhthemes")
```

## Example

I have found the core themes of \{ggplot2\} to have small text sizes. 
I also like more the Century Gothic family font. 
So we can edit both, as well as some other features, by "lucifying" a core theme. 

```{r}
library(fazhthemes)
library(tidyverse)

UKDriverDeaths_tibble <- UKDriverDeaths %>%
  matrix(nrow=16, ncol=12, byrow = TRUE,
         dimnames = list(1969:1984,month.abb)) %>%
  as.data.frame() %>%
  rownames_to_column("Year")

ggplot(data = UKDriverDeaths_tibble, aes(x=Year,y=Jan)) +
  geom_col(fill = "steelblue4", width = 0.1) +
  geom_point(color = "steelblue4", size = rel(10)) +
  theme_minimal()

```

```{r}
ggplot(data = UKDriverDeaths_tibble, aes(x=Year,y=Jan)) +
  geom_col(fill = "steelblue4", width = 0.1) +
  geom_point(color = "steelblue4", size = rel(10)) +
  lucify_theme_minimal()
```

